// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtsmvzjuevdfdfisygqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0c212emp1ZXZkZmRmaXN5Z3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzI2NjksImV4cCI6MjA3MDc0ODY2OX0.msWcGoc0lH465eNZWrSUgEfDNipzmu5SCxOGmHQlFsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});